[package]
name = "oxmud"
version = "0.1.0"
authors = ["Ajith Hussain <csy0013@googlemail.com>"]
edition = "2018"

[dependencies]
rustyline = "3.0.0"
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.13.0"
